---
- hosts: localhost
  become: True
  tasks:
    - name: Update all packages to latest version
      apt:
        name: "*"
        update_cache: yes
        state: latest
    - name: Install python pip
      apt:
        name: python3-pip
        state: present
    - name: Install docker
      apt:
        name: docker
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
        name: dockerdevserver
        image: "anilchelluru/mydockerdemo:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:9090:8080
